# Generated by Django 1.11.21 on 2019-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_api', '0002_auto_20190513_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='file_dpu',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
