CREATE DATABASE IF NOT EXISTS django_default;

CREATE USER IF NOT EXISTS 'django'@'%' IDENTIFIED BY '123456';
ALTER USER 'django'@'%' IDENTIFIED BY '123456';

GRANT ALL PRIVILEGES ON *.* TO 'django'@'%';

FLUSH PRIVILEGES;
