# Generated by Django 1.11.20 on 2019-05-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_workspace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Files',
        ),
    ]
